config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :transactions

  resources :exclusions

  resources :banks

  put '/recurrence/:id/advance' => 'recurrences#advance', :as => 'advance_recurrence'
  resources :recurrences

  resources :bills

  resources :accounts

  devise_for :users, controllers: { registrations: "users/registrations" }

  get 'dashboard' => 'dashboard#index'
  get 'dashboard_chart' => 'dashboard#chart'
  post 'skip_payment' => 'dashboard#skip_payment'
  post 'mark_paid' => 'dashboard#mark_paid'
  post 'generate_examples' => 'dashboard#generate_examples'

  get 'contact' => 'contact#index'
  post 'contact' => 'contact#create'

  root 'welcome#landing'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  respond_to :html, :js
  before_action :authenticate_user!
  before_action :set_recurrence, only: %i[skip_payment mark_paid]
  before_action :set_bank, only: %i[skip_payment mark_paid]

  def index
    @bills = current_user.bills
    @transaction = current_user.bank.transactions.new
    @forecast = ForecastTransactions.call(current_user) unless @bills.blank?
    @websites = current_user.bills.where.not(website: nil).pluck(:id, :website).to_h
  end

  def chart
    @bills = current_user.bills
    unless @bills.blank?
      @forecast = ForecastTransactions.call(current_user)
      @chart_data = CalculateBalanceChart.call(@forecast)
    end
    render json: @chart_data
  end

  # POST skip_payment?[:recurrence_id,:date]
  def skip_payment
    if @recurrence.once? && @recurrence.active_at.to_date.to_s == params[:date]
      @recurrence.update(active_at: @recurrence.next_date)
    else
      @exclusion = @recurrence.bill.exclusions.create(date: params[:date])
    end
    respond_to do |format|
      format.js { render action: "success" }
    end
  end

  # POST mark_paid?[:recurrence_id,:date,:amount]
  def mark_paid
    if @recurrence.once? || @recurrence.active_at.to_date.to_s != params[:date]
      @exclusion = @recurrence.bill.exclusions.new(date: params[:date])
    end
    # Create transaction with amount
    @transaction = current_user.bank.transactions.new(transaction_params)
    if @transaction.save
      @recurrence.update(active_at: @recurrence.next_date) unless @exclusion
      @exclusion&.save
      @bank.update(balance: @bank.balance + @transaction.amount)
    end
    respond_to do |format|
      format.js { render action: "success" }
    end
  end

  def generate_examples
    begin
      AddExampleData.call(current_user)
    rescue StandardError
      redirect_to dashboard_path, notice: "Examples added."
    else
      redirect_to dashboard_path, warning: "An error occurred adding examples."
    end
  end

  private

  def set_bank
    @bank = current_user.bank
  end

  def set_recurrence
    @recurrence = current_user.recurrences.find(params[:recurrence_id])
    @row_id = "#{params[:date]}_#{params[:recurrence_id]}"
    @balance = current_user.bank.balance
  end

  def transaction_params
    summary = @recurrence.bill.summary
    summary += " (#{@recurrence.note})" if @recurrence.note.present?
    params.permit(:date, :amount).merge(summary: summary)
  end
end

app/views/dashboard/index.html.haml
%script{:src => "https://d3js.org/d3.v4.min.js"}
%section
  .container.visitor-section
    .row.text-center
      %h1 Dashboard
      %hr.colored
    - unless @forecast
      .row
        .col
          .jumbotron
            %h1.text-center No Bills Found
            %p.lead
              Get started by adding some, 
              = link_to 'click to add.', bills_path
            %hr
            %h3.lead.text-black Need help getting started?
            = link_to 'Generate some examples', generate_examples_path, method: :post, class: 'btn-primary btn'
    - else
      .row
        .col-md-12
          .jumbotron.well
            = line_chart dashboard_chart_path
      .row
        .col
          .panel.panel-focus.filterable
            .panel-heading
              .row
                .col-md-3
                  %h3.panel-title
                    Forecasted Transactions
                .col-md-6
                  .balance-text="Starting Balance: $#{current_user.bank.balance}"
                  #readjustment-form.hide{style:'height:22px;'}
                    = render 'transactions/readjustment'
                .col-md-3{style: 'text-align: right;'}
                  %button.btn.btn-info.btn-xs#readjustment-button Change
            
            .table-responsive
              %table.table-focus.table.table-condensed.table-hover
                %thead
                  %tr
                    %th Date
                    %th Forcast
                    %th Change
                    %th{colspan: 2} Transaction
                    %th{colspan: 2} Link
                    %th.pull-right Actions
                %tbody
                  - @forecast.each do |f|
                    - f.each do |date,transactions|
                      %tr
                        - if transactions.count > 1
                          %th= date
                          - ending = transactions.last[:balance]
                          %th.lead{class: text_color_by_value(ending)}= "$ #{ending}"
                          - sum = transactions.map{|t| t[:amount]}.inject(:+)
                          %th.lead{class: text_color_by_value(sum)}= "$ #{sum}"
                          %th{colspan: 5}
                      - transactions.each do |transaction|
                        %tr{id: "#{date}_#{transaction[:recurrence_id]}"}
                          - class_size = 'small'
                          - if transactions.count == 1
                            %th= date
                            - class_size = 'lead'
                          - else
                            %th
                          %th{class: "#{text_color_by_value(transaction[:balance])} #{class_size}"}= "$ #{transaction[:balance]}"
                          %th{class: "#{text_color_by_value(transaction[:amount])} #{class_size}"}= "$ #{transaction[:amount]}"
                          %th= link_to transaction[:summary], bills_path+"/#{transaction[:bill_id]}"
                          %th= transaction[:note]
                          %th= build_website_link(@websites[transaction[:bill_id]])
                          %th
                            .btn-group.pull-right
                              = form_tag mark_paid_path, remote: true do
                                = hidden_field_tag 'amount', transaction[:amount]
                                = hidden_field_tag 'recurrence_id', transaction[:recurrence_id]
                                = hidden_field_tag 'date', date
                                = button_tag 'Mark Paid', class: 'btn btn-success btn-xs', data: { disable_with: "submitting"}
                          %th
                            .btn-group.pull-right
                              = form_tag skip_payment_path, remote: true do
                                = hidden_field_tag 'recurrence_id', transaction[:recurrence_id]
                                = hidden_field_tag 'date', date
                                = button_tag 'Skip', class: 'btn btn-info btn-xs', data: { disable_with: "submitting"}

app/views/dashboard/success.js.erb
$("#<%= escape_javascript(@row_id) %>").hide('fast')
$(".balance-text").html("Starting Balance: $<%= @balance %>")
Chartkick.charts["chart-1"].refreshData()