config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :transactions

  resources :exclusions

  resources :banks

  put '/recurrence/:id/advance' => 'recurrences#advance', :as => 'advance_recurrence'
  resources :recurrences

  resources :bills

  resources :accounts

  devise_for :users, controllers: { registrations: "users/registrations" }

  get 'dashboard' => 'dashboard#index'
  get 'dashboard_chart' => 'dashboard#chart'
  post 'skip_payment' => 'dashboard#skip_payment'
  post 'mark_paid' => 'dashboard#mark_paid'
  post 'generate_examples' => 'dashboard#generate_examples'

  get 'contact' => 'contact#index'
  post 'contact' => 'contact#create'

  root 'welcome#landing'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def landing; end
end

app/views/welcome/landing.html.haml
%section.jumbotron-bg.text-center
  %h1 Forecast your Finances
  %hr

%section.landing-splash
  .jumbotron.well.lead
    %p Take charge of your expenses!
    %p
      Devise a plan to divide, conquer and predict your finances through 
      Intelligent bill forecasting. Keep track of purchases and income and
      forecast your future balance.
      - if !user_signed_in?
        .pull-right
          Already have an account?
          = link_to 'Sign in', new_user_session_path
        = link_to 'Sign up!', new_user_registration_path, class: 'btn btn-lg btn-primary'
        
    

app/views/welcome/reinvite.html.haml
%section
  .container.visitor-section
    .row.text-center
      %h1 Resend Invitation
      %hr.colored
    .row
      .col-md-offset-4.col-md-4
        = form_tag({controller: "welcome", action: "invite"}, method: "put", role: "form") do -# "/users/invitation/resend", method: "put") do
          .form-group.float-label-control
            = label_tag :email, "Email"
            = email_field_tag :email, nil, class: 'form-control',placeholder: 'Email Address'
          %button.btn.btn-primary.btn-block{:type => "submit"} Resend me invitation instructions
          = link_to "Login", new_session_path(:user)
          .right= link_to "Forgot your password?", new_password_path(:user)