config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :transactions

  resources :exclusions

  resources :banks

  put '/recurrence/:id/advance' => 'recurrences#advance', :as => 'advance_recurrence'
  resources :recurrences

  resources :bills

  resources :accounts

  devise_for :users, controllers: { registrations: "users/registrations" }

  get 'dashboard' => 'dashboard#index'
  get 'dashboard_chart' => 'dashboard#chart'
  post 'skip_payment' => 'dashboard#skip_payment'
  post 'mark_paid' => 'dashboard#mark_paid'
  post 'generate_examples' => 'dashboard#generate_examples'

  get 'contact' => 'contact#index'
  post 'contact' => 'contact#create'

  root 'welcome#landing'
end

app/models/exclusion.rb
# frozen_string_literal: true

class Exclusion < ActiveRecord::Base
  belongs_to :bill

  validates_presence_of :bill

  default_scope { order('date ASC') }
end

app/controllers/exclusions_controller.rb
# frozen_string_literal: true

class ExclusionsController < ApplicationController
  respond_to :html, :js, :json
  before_action :authenticate_user!
  before_action :set_exclusion, only: %i[show edit update destroy]

  def index
    @exclusions = Exclusion.all
    respond_with(@exclusions)
  end

  def show
    respond_with(@exclusion)
  end

  def new
    @exclusion = Exclusion.new
    respond_with(@exclusion)
  end

  def edit; end

  def create
    @exclusion = Exclusion.new(exclusion_params)
    @exclusion.save
    respond_with(@exclusion)
  end

  def update
    @exclusion.update(exclusion_params)
    respond_with(@exclusion)
  end

  def destroy
    @exclusion.destroy
    redirect_to :back, notice: 'Exclusion deleted.'
  end

  private

  def set_exclusion
    @exclusion = Exclusion.find(params[:id])
  end

  def exclusion_params
    params.require(:exclusion).permit(:date, :bill_id)
  end
end

app/views/exclusions/_form.html.haml
/ = form_for(@exclusion, remote: true) do |f|
/   - if @exclusion.errors.any?
/     #error_explanation
/       %h2= "#{pluralize(@exclusion.errors.count, "error")} prohibited this exclusion from being saved:"
/       %ul
/         - @exclusion.errors.full_messages.each do |msg|
/           %li= msg
/
/   = f.label :date
/   = f.text_field :date, value: Time.now.to_date
/   = f.hidden_field :bill_id, value: bill.id
/   .actions
/     = f.submit 'Save'

.row
  .col-md-12.well{style:"margin-top:-12px;"}
    = form_for @exclusion, html: {role: 'form', class: 'form-horizontal', remote: true} do |f|
      .form-group
        .col-sm-offset-3.col-md-9
          %h3 New Exclusion
      - if @exclusion.errors.any?
        #error_explanation
          %h2
            = pluralize(@exclusion.errors.count, "error")
            prohibited this bill from being saved:
          %ul
            - @exclusion.errors.full_messages.each do |message|
              %li= messag
      = f.hidden_field :bill_id, value: bill.id
      .form-group
        %label.col-md-3.control-label{:for => "transaction_date"} Date
        .col-md-9
          = f.text_field :date, value: Time.now.strftime("%F"), placeholder: '(YYYY-MM-DD)', class: 'form-control'
      .form-group
        .col-md-offset-3.col-md-9
          %button.btn.btn-success.btn-md.btn-group{:type => "submit"} Create

app/views/exclusions/_index.html.haml
%div.table-responsive
  %table.table.table-condensed.table-hover
    %thead
      %tr
        %th Date
    %tbody
      - exclusions.each do |exclusion|
        %tr
          %td= best_in_place exclusion, :date, as: :input, :display_with => lambda { |v| v.to_date }
          %td
            = link_to_delete(exclusion)

app/views/exclusions/edit.html.haml
%h1 Editing exclusion

= render 'form'

= link_to 'Show', @exclusion
\|
= link_to 'Back', exclusions_path

app/views/exclusions/new.html.haml
%h1 New exclusion

= render 'form'

= link_to 'Back', exclusions_path

app/views/exclusions/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_exclusion_path(@exclusion)
\|
= link_to 'Back', exclusions_path