config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :transactions

  resources :exclusions

  resources :banks

  put '/recurrence/:id/advance' => 'recurrences#advance', :as => 'advance_recurrence'
  resources :recurrences

  resources :bills

  resources :accounts

  devise_for :users, controllers: { registrations: "users/registrations" }

  get 'dashboard' => 'dashboard#index'
  get 'dashboard_chart' => 'dashboard#chart'
  post 'skip_payment' => 'dashboard#skip_payment'
  post 'mark_paid' => 'dashboard#mark_paid'
  post 'generate_examples' => 'dashboard#generate_examples'

  get 'contact' => 'contact#index'
  post 'contact' => 'contact#create'

  root 'welcome#landing'
end

app/views/navigation/_bar.html.haml
%nav.navbar.navbar-fixed-top.navbar-inverse{role: 'navigation'}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      
      = link_to user_signed_in? ? dashboard_path : root_url, class: 'navbar-brand' do
        = image_tag("apple-touch-icon.png", size: '32', class:"brand-img",alt:'')
        %span.brand-header Finance Forecaster
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          = render partial: 'navigation/nav_link', locals: {nav_icon: 'fa-chart-line',nav_text: 'Dashboard',nav_path: dashboard_path}
          = render partial: 'navigation/nav_link', locals: {nav_icon: 'fa-money-check-alt',nav_text: 'Bills',nav_path: bills_path}
          = render partial: 'navigation/nav_link', locals: {nav_icon: 'fa-exchange-alt',nav_text: 'Transactions',nav_path: transactions_path}
          %li
            = link_to('Sign out', destroy_user_session_path, :method => :delete)
        - else
          = render partial: 'navigation/nav_link', locals: {nav_text: 'Sign up',nav_path: new_user_registration_path,nav_icon:nil}
          = render partial: 'navigation/nav_link', locals: {nav_text: 'Login',nav_path: new_user_session_path,nav_icon:nil}

app/views/navigation/_nav_link.html.haml
%li{class: "#{'active' if (controller_name == nav_text.downcase || current_page?(nav_path) )}"}
  %a{:href => nav_path}
    - if nav_icon
      %i.fas{class: nav_icon} 
    = nav_text